<?php

declare(strict_types=1);

namespace Travel\Components\TicketTravel\Features\Segment\SmartTravel;

enum ErrorCode: int
{
    // CONDITION
    case FAILED_TO_CREATE_NUMBER_CONDITION = 20301;
    case FAILED_TO_CREATE_TEXT_CONDITION = 20302;
    case FAILED_TO_CREATE_FILTER_CONDITION = 20303;
    case FAILED_TO_UPDATE_NUMBER_CONDITION = 20304;
    case FAILED_TO_UPDATE_TEXT_CONDITION = 20305;
    case FAILED_TO_UPDATE_FILTER_CONDITION = 20306;
    case FAILED_TO_DELETE_CONDITION = 20307;
    case FAILED_TO_DELETE_FILTER = 20308;
    // TRAVEL
    case FAILED_TO_READ_SMART_TRAVEL = 20309;
    case FAILED_TO_CREATE_SMART_TRAVEL = 20310;
    case FAILED_TO_RENAME_SMART_TRAVEL = 20311;
    case FAILED_TO_DELETE_SMART_TRAVEL = 20312;
    case FAILED_TO_CREATE_QUERY = 20313;
}
