apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "travel.fullname" . }}-migration"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation 
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1        

  template:
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ include "travel.fullname" . }}-migration
        image: "{{ .Values.image_fpm.repository }}:{{ .Values.image_fpm.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image_fpm.pullPolicy }}        
        command: ["/bin/sh", "-c"]
        args: {{ .Values.args }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Never

