apiVersion: v1
kind: Service
metadata:
  name: {{ include "travel.fullname" . }}
  labels:
    {{- include "travel.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 81
      protocol: TCP
      name: http
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: php
        
  selector:
    {{- include "travel.selectorLabels" . | nindent 4 }}
